--[[
	EconomyService
	All coin/gem mutations funnel through here so numbers always stay
	server-authoritative and get pushed to the client via Remotes.DataUpdated.

	Place: ServerScriptService/Services/EconomyService.lua (ModuleScript)
	Orchestrated by: ServerScriptService/Main.server.lua
]]

local ReplicatedStorage = game:GetService("ReplicatedStorage")

local EconomyData = require(ReplicatedStorage.Modules.EconomyData)
local UpgradeData = require(ReplicatedStorage.Modules.UpgradeData)
local Remotes = require(ReplicatedStorage.Modules.Remotes)

local EconomyService = {}

local PlayerDataService -- late-bound in Init to avoid circular require order issues

local function pushSnapshot(player)
	local profile = PlayerDataService.GetData(player)
	if profile then
		Remotes.DataUpdated:FireClient(player, profile)
	end
end

function EconomyService.AddCoins(player, amount, _reason)
	if amount == nil or amount ~= amount or amount == math.huge then
		return
	end
	local profile = PlayerDataService.GetData(player)
	if not profile then
		return
	end
	amount = math.floor(amount)
	if amount <= 0 then
		return
	end
	profile.Coins += amount
	profile.Stats.TotalCoinsEarned += amount
	PlayerDataService.MarkDirty(player)
	pushSnapshot(player)
end

function EconomyService.SpendCoins(player, amount)
	local profile = PlayerDataService.GetData(player)
	if not profile or amount == nil or amount <= 0 then
		return false
	end
	if profile.Coins < amount then
		return false
	end
	profile.Coins -= amount
	PlayerDataService.MarkDirty(player)
	pushSnapshot(player)
	return true
end

function EconomyService.AddGems(player, amount)
	local profile = PlayerDataService.GetData(player)
	if not profile or amount == nil or amount <= 0 then
		return
	end
	profile.Gems += math.floor(amount)
	PlayerDataService.MarkDirty(player)
	pushSnapshot(player)
end

function EconomyService.SpendGems(player, amount)
	local profile = PlayerDataService.GetData(player)
	if not profile or amount == nil or amount <= 0 then
		return false
	end
	if profile.Gems < amount then
		return false
	end
	profile.Gems -= amount
	PlayerDataService.MarkDirty(player)
	pushSnapshot(player)
	return true
end

-- Computes pending passive income (in coins) generated by all owned habitats
-- since the player's last claim, capped by EconomyData.MaxOfflinePassiveMinutes.
function EconomyService.GetPendingPassiveIncome(player)
	local profile = PlayerDataService.GetData(player)
	if not profile then
		return 0
	end

	local minutesElapsed = math.min((os.time() - profile.LastIncomeClaim) / 60, EconomyData.MaxOfflinePassiveMinutes)
	if minutesElapsed <= 0 then
		return 0
	end

	local totalLevel = 0
	for _, level in pairs(profile.HabitatLevels) do
		totalLevel += level
	end

	local base = totalLevel * EconomyData.PassiveIncomePerHabitatLevel * minutesElapsed
	local bonusPercent = 0
	for brainrotId, level in pairs(profile.HabitatLevels) do
		local levelInfo = UpgradeData.GetLevelInfo(level)
		if levelInfo then
			bonusPercent += levelInfo.CoinBonusPercent
		end
	end

	return math.floor(base * (1 + bonusPercent / 100))
end

function EconomyService.ClaimPassiveIncome(player)
	local profile = PlayerDataService.GetData(player)
	if not profile then
		return 0
	end
	local pending = EconomyService.GetPendingPassiveIncome(player)
	profile.LastIncomeClaim = os.time()
	if pending > 0 then
		EconomyService.AddCoins(player, pending, "PassiveIncome")
	else
		PlayerDataService.MarkDirty(player)
	end
	return pending
end

function EconomyService.Init(services)
	PlayerDataService = services.PlayerDataService

	Remotes.ClaimReward.OnServerEvent:Connect(function(player, rewardType)
		if rewardType == "PassiveIncome" then
			EconomyService.ClaimPassiveIncome(player)
		end
	end)
end

return EconomyService
